class Libbook {
  final int id;
  final String name;
  final String author;
  final String description;
  final String genre;
  final String img;
  final int library_Libbookid;
  final int Qntity;
  final int available;

  Libbook({
    required this.id,
    required this.name,
    required this.author,
    required this.description,
    required this.genre,
    required this.img,
    required this.library_Libbookid,
    required this.Qntity,
    required this.available,
  });
}

List<Libbook> Libbooks = [
  Libbook(
    id: 201,
    name: "Introduction to the Theory of Computation",
    author: "Michael Sipser",
    description: "A comprehensive guide to computational theory, automata, and complexity.",
    genre: "Computer Science, Theory",
    img: "assets/images/img1.jpg",
    library_Libbookid: 1001,
    Qntity: 10,
    available: 7,
  ),
  Libbook(
    id: 202,
    name: "Artificial Intelligence: A Modern Approach",
    author: "Stuart Russell, Peter Norvig",
    description: "The standard AI textLibbook covering search, learning, and deep AI concepts.",
    genre: "Artificial Intelligence, Machine Learning",
    img: "assets/images/img2.jpg",
    library_Libbookid: 1002,
    Qntity: 8,
    available: 5,
  ),
  Libbook(
    id: 203,
    name: "Clean Code",
    author: "Robert C. Martin",
    description: "Guidelines for writing maintainable, high-quality, and clean software code.",
    genre: "Software Development, Best Practices",
    img: "assets/images/img3.jpg",
    library_Libbookid: 1003,
    Qntity: 12,
    available: 9,
  ),
  Libbook(
    id: 204,
    name: "Computer Networking: A Top-Down Approach",
    author: "James F. Kurose, Keith W. Ross",
    description: "Explains networking concepts starting from application layer to the physical layer.",
    genre: "Networking, Computer Science",
    img: "assets/images/img4.jpg",
    library_Libbookid: 1004,
    Qntity: 6,
    available: 0,
  ),
  Libbook(
    id: 205,
    name: "The C Programming Language",
    author: "Brian W. Kernighan, Dennis M. Ritchie",
    description: "A foundational Libbook for learning the C programming language from the creators.",
    genre: "Programming, Systems",
    img: "assets/images/img5.jpg",
    library_Libbookid: 1005,
    Qntity: 9,
    available: 4,
  ),
  Libbook(
    id: 206,
    name: "Introduction to Algorithms",
    author: "Thomas H. Cormen, Charles E. Leiserson, Ronald L. Rivest, Clifford Stein",
    description: "A detailed and theoretical guide on algorithms used in computing.",
    genre: "Algorithms, Computer Science",
    img: "assets/images/img6.jpg",
    library_Libbookid: 1006,
    Qntity: 15,
    available: 10,
  ),
  Libbook(
    id: 207,
    name: "Design Patterns: Elements of Reusable Object-Oriented Software",
    author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
    description: "A classic Libbook explaining fundamental design patterns in software development.",
    genre: "Software Engineering, Programming",
    img: "assets/images/img7.jpg",
    library_Libbookid: 1007,
    Qntity: 7,
    available: 5,
  ),
  Libbook(
    id: 208,
    name: "Operating System Concepts",
    author: "Abraham Silberschatz, Peter B. Galvin, Greg Gagne",
    description: "Comprehensive knowledge of modern operating systems and their concepts.",
    genre: "Operating Systems, Computer Science",
    img: "assets/images/img8.jpg",
    library_Libbookid: 1008,
    Qntity: 11,
    available: 6,
  ),
  Libbook(
    id: 209,
    name: "Database System Concepts",
    author: "Abraham Silberschatz, Henry F. Korth, S. Sudarshan",
    description: "A complete guide to database management systems and SQL.",
    genre: "Databases, Computer Science",
    img: "assets/images/img9.jpg",
    library_Libbookid: 1009,
    Qntity: 13,
    available: 9,
  ),
  Libbook(
    id: 210,
    name: "Deep Learning",
    author: "Ian Goodfellow, Yoshua Bengio, Aaron Courville",
    description: "A fundamental Libbook on deep learning concepts and neural networks.",
    genre: "Machine Learning, Artificial Intelligence",
    img: "assets/images/img10.jpg",
    library_Libbookid: 1010,
    Qntity: 5,
    available: 2,
  ),
  Libbook(
    id: 211,
    name: "You Don't Know JS",
    author: "Kyle Simpson",
    description: "A deep dive into JavaScript concepts, closures, scope, and asynchronous programming.",
    genre: "Web Development, JavaScript",
    img: "assets/images/img11.jpg",
    library_Libbookid: 1011,
    Qntity: 8,
    available: 4,
  ),
  Libbook(
    id: 212,
    name: "The Pragmatic Programmer",
    author: "Andrew Hunt, David Thomas",
    description: "A must-read Libbook on software craftsmanship and best coding practices.",
    genre: "Software Engineering, Development",
    img: "assets/images/img12.jpg",
    library_Libbookid: 1012,
    Qntity: 6,
    available: 3,
  ),
  Libbook(
    id: 213,
    name: "The Mythical Man-Month",
    author: "Frederick P. Brooks Jr.",
    description: "Insights into software project management and engineering principles.",
    genre: "Software Project Management",
    img: "assets/images/img13.jpg",
    library_Libbookid: 1013,
    Qntity: 7,
    available: 4,
  ),
  Libbook(
    id: 214,
    name: "Structure and Interpretation of Computer Programs",
    author: "Harold Abelson, Gerald Jay Sussman",
    description: "A classic programming Libbook emphasizing recursion, abstraction, and interpretation.",
    genre: "Programming, Computer Science",
    img: "assets/images/img14.jpg",
    library_Libbookid: 1014,
    Qntity: 9,
    available: 5,
  ),
  Libbook(
    id: 215,
    name: "Cryptography and Network Security",
    author: "William Stallings",
    description: "A complete guide to cryptographic principles and secure communication.",
    genre: "Cybersecurity, Cryptography",
    img: "assets/images/img15.jpg",
    library_Libbookid: 1015,
    Qntity: 10,
    available: 6,
  ),
  Libbook(
    id: 216,
    name: "The Design of Everyday Things",
    author: "Don Norman",
    description: "A UX design Libbook explaining how to create user-friendly technology.",
    genre: "User Experience, Design",
    img: "assets/images/img16.jpg",
    library_Libbookid: 1016,
    Qntity: 4,
    available: 2,
  ),
];
